config:
  aws:region: us-west-2
  aws:allowedAccountIds:
    - "922751599449"
secretsprovider: awskms:///arn:aws:kms:us-west-2:195969062870:key/db6a398f-c0e3-4180-86c5-227ef790beb0?region=us-west-2
encryptedkey: AQICAHjkVGG1RYvy4iBbs4Uoh7cKKMTvt+NKiUd3hOxC7baRbQHmICRJsvBBxobIioLVrDRKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZ/nr/WHYeqQBjbMhAgEQgDtb0TOsamF5lngtjrRGeKIrf4FTwOuRFzMqBb3EQA7YfTO7sM5ipErgaCf4e+byDgXm8KTlpWy7Cid7Mg==
